# Generated by Django 6.0 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
    ]
