# Generated by Django 6.0 on 2026-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctorregister_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
