# Generated by Django 6.0 on 2026-02-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_checkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.doctorregister'),
        ),
    ]
