# Generated by Django 6.0 on 2026-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_doctoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
